# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
