# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_grapher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BandNameInput',
        ),
    ]
