# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This is the default description', max_length=400),
            preserve_default=False,
        ),
    ]
